# Generated by Django 5.1.3 on 2024-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='senha_temporal', max_length=16),
        ),
    ]
