# Generated by Django 5.1.3 on 2024-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_cliente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente - Garçom'), ('CAIXA', 'Caixa'), ('GERENTE', 'Gerente')], default='Desconhecido', max_length=50),
        ),
    ]
